In [1]:
import numpy as np
import pandas as pd

In [17]:
data = {
    "Date": pd.date_range('2023-01-01',periods = 20),
    "product": ['A','B','C','D'] *5,
    "region": ["North","West", "South","East","North",
    "West", "South","East","North","West", "South","East",
    "North","West", "South","East","North","West", "South","East"
    ],
    "sales": np.random.randint(100,1000,20),
    "units": np.random.randint(10,100,20),
    "rep": ["Alice","Bob","Carol","David","Emma","Frank","Grace","Henry","Isa",
    "Jack","Kath","Liam","Mia","Noa","Oly","Paul","Quinn","Ryan","Sopi","Tom"]
}
df = pd.DataFrame(data)
df['Month'] = df['Date'].dt.month_name()
df["Quarter"] = 'Q' + df["Date"].dt.quarter.astype(str)
df

         Date product region  sales  units    rep    Month Quarter
0  2023-01-01       A  North    332     16  Alice  January      Q1
1  2023-01-02       B   West    828     19    Bob  January      Q1
2  2023-01-03       C  South    822     92  Carol  January      Q1
3  2023-01-04       D   East    895     83  David  January      Q1
4  2023-01-05       A  North    425     11   Emma  January      Q1
5  2023-01-06       B   West    223     19  Frank  January      Q1
6  2023-01-07       C  South    467     25  Grace  January      Q1
7  2023-01-08       D   East    435     37  Henry  January      Q1
8  2023-01-09       A  North    456     63    Isa  January      Q1
9  2023-01-10       B   West    456     82   Jack  January      Q1
10 2023-01-11       C  South    960     27   Kath  January      Q1
11 2023-01-12       D   East    260     71   Liam  January      Q1
12 2023-01-13       A  North    864     47    Mia  January      Q1
13 2023-01-14       B   West    546     10    Noa  January      Q1
14 2023-01-15       C  South    136     63    Oly  January      Q1
15 2023-01-16       D   East    836     16   Paul  January      Q1
16 2023-01-17       A  North    655     92  Quinn  January      Q1
17 2023-01-18       B   West    885     35   Ryan  January      Q1
18 2023-01-19       C  South    344     56   Sopi  January      Q1
19 2023-01-20       D   East    833     92    Tom  January      Q1

In [20]:
pd.pivot_table(df, values = 'sales', index = 'region', columns = 'product', aggfunc = 'median')

product      A      B      C      D
region
East       NaN    NaN    NaN  833.0
North    456.0    NaN    NaN    NaN
South      NaN    NaN  467.0    NaN
West       NaN  546.0    NaN    NaN

In [24]:
pivot2 = pd.pivot_table(df, values = ['sales','units'], index = 'region', columns = 'product', aggfunc = 'median')
pivot2

         sales                      units
product      A      B      C      D     A     B     C     D
region
East       NaN    NaN    NaN  833.0   NaN   NaN   NaN  71.0
North    456.0    NaN    NaN    NaN  47.0   NaN   NaN   NaN
South      NaN    NaN  467.0    NaN   NaN   NaN  56.0   NaN
West       NaN  546.0    NaN    NaN   NaN  19.0   NaN   NaN

Cross Tabs

In [26]:
#Cross tabs are similar to pivot table but it is used for counting purpose not aggregation
pd.crosstab(df['product'],df['region'])

region   East  North  South  West
product
A           0      5      0     0
B           0      0      0     5
C           0      0      5     0
D           5      0      0     0

In [28]:
pd.crosstab(df['region'],df['product'])

product  A  B  C  D
region
East     0  0  0  5
North    5  0  0  0
South    0  0  5  0
West     0  5  0  0